#Introduction


Netflix adalah platform layanan streaming digital yang menyediakan berbagai jenis hiburan seperti film, serial TV, dokumenter, anime, dan tayangan original yang dapat diakses melalui internet. Netflix beroperasi secara global dan memiliki jutaan pengguna di berbagai negara.

Dataset Netflix berisi kumpulan Movies dan TV Show pada Netflix. Dataset ini berisi kumpulan data Movie dan TV Show yang tersedia pada platform Netflix. Dataset ini mencakup berbagai informasi seperti jenis konten (type), judul (title), sutradara (director), negara produksi (country), tahun rilis (release_year), rating usia (rating), genre (listed_in), serta tanggal penambahan konten ke Netflix (date_added).

Analisis dataset Netflix dilakukan untuk menganalisis distribusi konten Netflix berdasarkan jenis tayangan, negara produksi, genre, rating usia, tahun rilis, waktu penambahan konten, dan perkembangan konten dari waktu ke waktu. Analisis dilakukan untuk memahami karakteristik katalog Netflix dan memperoleh insight terkait strategi konten serta segmentasi target penonton.

# Import Library

In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Read Data

In [2]:
df = pd.read_csv("https://raw.github.com/nadiraaini77/python-data-analyst/180ae2968df4b559a749e8a748a812321e424109/netflix.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

# Info Data

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

# Describe Data

In [4]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

# Cek Missing Value

In [5]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

# Cek Duplikat

In [6]:
df.duplicated().sum()

np.int64(0)

# Isi Missing Value

In [7]:
# isi missing value country
df['country'] = df['country'].fillna(df['country'].mode()[0])

In [8]:
# isi missing value rating
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

In [9]:
# isi missing value duration
df['duration'] = df['duration'].fillna(df['duration'].mode()[0])

In [10]:
# isi missing value date_added
df['date_added'] = df['date_added'].fillna(df['date_added'].mode()[0])

In [11]:
# cek missing value
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country            0
date_added         0
release_year       0
rating             0
duration           0
listed_in          0
description        0
dtype: int64

# Ubah date_added menjadi format tanggal

In [12]:
# Hapus spasi kosong
df['date_added'] = df['date_added'].str.strip()

In [13]:
# Ubah ke datetime
df['date_added'] = pd.to_datetime(df['date_added'])

In [14]:
#tambah kolom baru untuk year_added
df['year_added'] = df['date_added'].dt.year

In [15]:
#ganti tipe data year_added ke int
df['year_added'] = df['year_added'].astype(int)

In [16]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,United States,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021

# Mengelompokkan rating

In [17]:
# cek data uniq di rating
df['rating'].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', '74 min', '84 min', '66 min', 'NR',
       'TV-Y7-FV', 'UR'], dtype=object)

In [18]:
# ubah data error menjadi nan
df.loc[df['rating'].str.contains('min', na=False), 'rating'] = None

In [19]:
# isi missing value rating
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

In [20]:
def rating_group(rating):
    if rating in ['TV-MA', 'R', 'NC-17']:
        return 'Adult'
    elif rating in ['PG-13', 'PG', 'TV-PG', 'TV-14']:
        return 'Teens'
    elif rating in ['TV-Y7', 'TV-Y', 'TV-Y7-FV']:
        return 'Children'
    else:
        return 'General'

In [21]:
# buat kolom rating_group
df['rating_group'] = df['rating'].apply(rating_group)

In [22]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,rating_group
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,Teens
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,Adult
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,Adult
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,United States,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,Adult
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,Adult

# Membersihkan kolom country

In [23]:
# hapus spasi dan koma
df['country'] = df['country'].str.strip()

In [24]:
# pisahkan negara
df['country'] = df['country'].str.split(', ')

In [25]:
# explode negara
df = df.explode('country')

In [26]:
# hapus spasi
df['country'] = df['country'].str.strip()

# DataFrame to SQL

In [28]:
pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 48.0 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [29]:
import pandas as pd

In [30]:
from sqlalchemy import create_engine

In [31]:
DATABASE_URL = (
"postgresql://postgres.ssgquzqdkmuqaudouvxo:aaiinnii2003@aws-1-ap-south-1.pooler.supabase.com:6543/postgres"
)

engine = create_engine(DATABASE_URL)

In [32]:
df.to_sql("netflix",engine,if_exists="replace",index=False)

845

# Insight

## 1. Distribusi jenis konten

In [33]:
df['type'].value_counts()

type
Movie      7814
TV Show    3031
Name: count, dtype: int64

Tipe konten Movie mendominasi di Netflix dibandingkan dengan TV Show.

## 2. Negara produsen konten terbanyak di neftlix

In [77]:
df.groupby('type')['country'].value_counts()

type     country
Movie    United States           3191
         India                    962
         United Kingdom           532
         Canada                   319
         France                   303
         Germany                  182
         Spain                    171
         Japan                    119
         China                    114
         Mexico                   111
         Egypt                    102
         Hong Kong                100
         Australia                 94
         Nigeria                   94
         Indonesia                 86
         Turkey                    83
         Philippines               80
         Belgium                   78
         Italy                     75
         Argentina                 71
         Brazil                    66
         South Korea               61
         South Africa              51
         Thailand                  46
         Netherlands               42
         United Arab Emirates      36
         Denmark                   34
         Ireland                   32
         Poland                    31
         Sweden                    31
         New Zealand               25
         Chile                     24
         Lebanon                   24
         Norway                    21
         Colombia                  20
         Pakistan                  20
         Israel                    19
         Taiwan                    19
         Malaysia                  18
         Singapore                 18
         Switzerland               18
         Czech Republic            16
         Romania                   14
         Uruguay                   13
         Austria                   11
         Russia                    11
         Bulgaria                  10
         Hungary                   10
         Luxembourg                10
         Peru                      10
         Qatar                     10
         Greece                     9
         Saudi Arabia               9
         Iceland                    8
         Finland                    7
         Jordan                     7
         Serbia                     7
         Vietnam                    7
         Kenya                      6
         Morocco                    6
         Portugal                   6
         Cambodia                   5
         Ghana                      5
         Kuwait                     5
         Bangladesh                 4
         Iran                       4
         Venezuela                  4
         Algeria                    3
         Croatia                    3
         Slovenia                   3
         Soviet Union               3
         West Germany               3
         Zimbabwe                   3
         Cayman Islands             2
         Georgia                    2
         Guatemala                  2
         Iraq                       2
         Malta                      2
         Namibia                    2
         Nepal                      2
         Senegal                    2
         Syria                      2
         United Kingdom,            2
                                    1
         Afghanistan                1
         Albania                    1
         Angola                     1
         Armenia                    1
         Bahamas                    1
         Bermuda                    1
         Botswana                   1
         Burkina Faso               1
         Cambodia,                  1
         Cameroon                   1
         Dominican Republic         1
         East Germany               1
         Ecuador                    1
         Ethiopia                   1
         Jamaica                    1
         Kazakhstan                 1
         Latvia                     1
         Liechtenstein              1
         Lithuania                  1
         Malawi                     1
         Mauritius                  1
         Mongolia                   1
         Montenegro                 1
         Mozambique                 1
         Nicaragua                  1
         Palestine                  1
         Panama                     1
         Paraguay                   1
         Poland,                    1
         Samoa                      1
         Slovakia                   1
         Somalia                    1
         Sri Lanka                  1
         Sudan                      1
         Uganda                     1
         Ukraine                    1
         United States,             1
         Vatican City               1
TV Show  United States           1329
         United Kingdom           272
         Japan                    199
         South Korea              170
         Canada                   126
         France                    90
         India                     84
         Taiwan                    70
         Australia                 66
         Spain                     61
         Mexico                    58
         China                     48
         Germany                   44
         Colombia                  32
         Brazil                    31
         Turkey                    30
         Italy                     25
         Thailand                  24
         Singapore                 23
         Argentina                 20
         Russia                    16
         Egypt                     15
         Denmark                   14
         Ireland                   14
         Belgium                   12
         Israel                    11
         South Africa              11
         Sweden                    11
         Nigeria                    9
         Norway                     9
         Poland                     9
         Malaysia                   8
         Netherlands                8
         New Zealand                8
         Lebanon                    7
         Czech Republic             6
         Chile                      5
         Hong Kong                  5
         Finland                    4
         Indonesia                  4
         Pakistan                   4
         Saudi Arabia               4
         Iceland                    3
         Kuwait                     3
         Philippines                3
         Greece                     2
         Jordan                     2
         Luxembourg                 2
         Ukraine                    2
         West Germany               2
                                    1
         Austria                    1
         Azerbaijan                 1
         Belarus                    1
         Croatia                    1
         Cuba                       1
         Cyprus                     1
         Hungary                    1
         Malta                      1
         Mauritius                  1
         Puerto Rico                1
         Senegal                    1
         Switzerland                1
         Syria                      1
         United Arab Emirates       1
         Uruguay                    1
Name: count, dtype: int64

In [76]:
df.groupby('type')['country'].value_counts()

type     country
Movie    United States           3191
         India                    962
         United Kingdom           532
         Canada                   319
         France                   303
         Germany                  182
         Spain                    171
         Japan                    119
         China                    114
         Mexico                   111
         Egypt                    102
         Hong Kong                100
         Australia                 94
         Nigeria                   94
         Indonesia                 86
         Turkey                    83
         Philippines               80
         Belgium                   78
         Italy                     75
         Argentina                 71
         Brazil                    66
         South Korea               61
         South Africa              51
         Thailand                  46
         Netherlands               42
         United Arab Emirates      36
         Denmark                   34
         Ireland                   32
         Poland                    31
         Sweden                    31
         New Zealand               25
         Chile                     24
         Lebanon                   24
         Norway                    21
         Colombia                  20
         Pakistan                  20
         Israel                    19
         Taiwan                    19
         Malaysia                  18
         Singapore                 18
         Switzerland               18
         Czech Republic            16
         Romania                   14
         Uruguay                   13
         Austria                   11
         Russia                    11
         Bulgaria                  10
         Hungary                   10
         Luxembourg                10
         Peru                      10
         Qatar                     10
         Greece                     9
         Saudi Arabia               9
         Iceland                    8
         Finland                    7
         Jordan                     7
         Serbia                     7
         Vietnam                    7
         Kenya                      6
         Morocco                    6
         Portugal                   6
         Cambodia                   5
         Ghana                      5
         Kuwait                     5
         Bangladesh                 4
         Iran                       4
         Venezuela                  4
         Algeria                    3
         Croatia                    3
         Slovenia                   3
         Soviet Union               3
         West Germany               3
         Zimbabwe                   3
         Cayman Islands             2
         Georgia                    2
         Guatemala                  2
         Iraq                       2
         Malta                      2
         Namibia                    2
         Nepal                      2
         Senegal                    2
         Syria                      2
         United Kingdom,            2
                                    1
         Afghanistan                1
         Albania                    1
         Angola                     1
         Armenia                    1
         Bahamas                    1
         Bermuda                    1
         Botswana                   1
         Burkina Faso               1
         Cambodia,                  1
         Cameroon                   1
         Dominican Republic         1
         East Germany               1
         Ecuador                    1
         Ethiopia                   1
         Jamaica                    1
         Kazakhstan                 1
         Latvia                     1
         Liechtenstein              1
         Lithuania                  1
         Malawi                     1
         Mauritius                  1
         Mongolia                   1
         Montenegro                 1
         Mozambique                 1
         Nicaragua                  1
         Palestine                  1
         Panama                     1
         Paraguay                   1
         Poland,                    1
         Samoa                      1
         Slovakia                   1
         Somalia                    1
         Sri Lanka                  1
         Sudan                      1
         Uganda                     1
         Ukraine                    1
         United States,             1
         Vatican City               1
TV Show  United States           1329
         United Kingdom           272
         Japan                    199
         South Korea              170
         Canada                   126
         France                    90
         India                     84
         Taiwan                    70
         Australia                 66
         Spain                     61
         Mexico                    58
         China                     48
         Germany                   44
         Colombia                  32
         Brazil                    31
         Turkey                    30
         Italy                     25
         Thailand                  24
         Singapore                 23
         Argentina                 20
         Russia                    16
         Egypt                     15
         Denmark                   14
         Ireland                   14
         Belgium                   12
         Israel                    11
         South Africa              11
         Sweden                    11
         Nigeria                    9
         Norway                     9
         Poland                     9
         Malaysia                   8
         Netherlands                8
         New Zealand                8
         Lebanon                    7
         Czech Republic             6
         Chile                      5
         Hong Kong                  5
         Finland                    4
         Indonesia                  4
         Pakistan                   4
         Saudi Arabia               4
         Iceland                    3
         Kuwait                     3
         Philippines                3
         Greece                     2
         Jordan                     2
         Luxembourg                 2
         Ukraine                    2
         West Germany               2
                                    1
         Austria                    1
         Azerbaijan                 1
         Belarus                    1
         Croatia                    1
         Cuba                       1
         Cyprus                     1
         Hungary                    1
         Malta                      1
         Mauritius                  1
         Puerto Rico                1
         Senegal                    1
         Switzerland                1
         Syria                      1
         United Arab Emirates       1
         Uruguay                    1
Name: count, dtype: int64

United State merupakan negara dengan kontribusi konten terbesar untuk Movie maupun TV Show, diikuti oleh India untuk Movie dan United Kigdom untuk TV Show.

## 3. Rating konten antar negara produksi

In [73]:
df.groupby('country')['rating_group'].value_counts().reset_index(name='count').sort_values(by='count',ascending=False)

                  country rating_group  count
254         United States        Adult   2052
255         United States        Teens   1811
99                  India        Teens    734
256         United States     Children    455
249        United Kingdom        Adult    396
250        United Kingdom        Teens    320
100                 India        Adult    271
76                 France        Adult    221
257         United States      General    202
41                 Canada        Adult    187
221                 Spain        Adult    184
121                 Japan        Teens    169
42                 Canada        Teens    153
81                Germany        Adult    122
77                 France        Teens    116
149                Mexico        Adult    116
122                 Japan        Adult    111
216           South Korea        Teens    108
217           South Korea        Adult     94
49                  China        Teens     91
82                Germany        Teens     83
69                  Egypt        Teens     83
43                 Canada     Children     81
240                Turkey        Adult     69
7               Argentina        Adult     69
12              Australia        Adult     66
24                Belgium        Adult     64
13              Australia        Teens     64
30                 Brazil        Adult     62
103             Indonesia        Teens     60
170               Nigeria        Teens     57
116                 Italy        Adult     56
50                  China        Adult     54
235                Taiwan        Teens     53
91              Hong Kong        Adult     52
92              Hong Kong        Teens     51
237              Thailand        Adult     47
251        United Kingdom     Children     46
183           Philippines        Teens     44
171               Nigeria        Adult     44
252        United Kingdom      General     42
78                 France     Children     42
241                Turkey        Teens     41
150                Mexico        Teens     40
213          South Africa        Adult     37
222                 Spain        Teens     37
236                Taiwan        Adult     36
123                 Japan     Children     35
184           Philippines        Adult     35
53               Colombia        Adult     35
186                Poland        Adult     34
70                  Egypt        Adult     33
227                Sweden        Adult     31
117                 Italy        Teens     30
62                Denmark        Adult     28
161           Netherlands        Adult     27
31                 Brazil        Teens     25
110               Ireland        Adult     25
214          South Africa        Teens     24
101                 India     Children     24
44                 Canada      General     24
246  United Arab Emirates        Teens     23
218           South Korea     Children     23
47                  Chile        Adult     23
238              Thailand        Teens     22
206             Singapore        Teens     22
173                Norway        Adult     21
14              Australia     Children     21
104             Indonesia        Adult     21
175              Pakistan        Teens     20
142              Malaysia        Teens     19
25                Belgium        Teens     19
114                Israel        Adult     18
102                 India      General     17
54               Colombia        Teens     16
207             Singapore        Adult     16
134               Lebanon        Teens     16
165           New Zealand        Adult     16
135               Lebanon        Adult     15
8               Argentina        Teens     15
79                 France      General     14
162           Netherlands        Teens     14
166           New Zealand        Teens     13
83                Germany      General     12
247  United Arab Emirates        Adult     12
196                Russia        Adult     12
115                Israel        Teens     12
60         Czech Republic        Adult     12
111               Ireland        Teens     12
200          Saudi Arabia        Teens     11
118                 Italy     Children     11
230           Switzerland        Adult     11
51                  China     Children     11
194               Romania        Adult     10
63                Denmark        Teens     10
61         Czech Republic        Teens     10
228                Sweden        Teens     10
34               Bulgaria        Adult      9
84                Germany     Children      9
174                Norway        Teens      9
15              Australia      General      9
94                Hungary        Adult      9
259               Uruguay        Adult      9
197                Russia     Children      8
105             Indonesia      General      8
87                 Greece        Teens      8
151                Mexico      General      7
198                Russia        Teens      7
131                Kuwait        Teens      7
97                Iceland        Adult      7
231           Switzerland        Teens      7
16                Austria        Adult      7
52                  China      General      6
223                 Spain     Children      6
48                  Chile        Teens      6
152                Mexico     Children      6
138            Luxembourg        Adult      6
32                 Brazil      General      6
112               Ireland     Children      6
219           South Korea      General      6
187                Poland        Teens      6
125                Jordan        Adult      5
9               Argentina      General      5
17                Austria        Teens      5
224                 Spain      General      5
139            Luxembourg        Teens      5
163           Netherlands      General      5
189              Portugal        Adult      5
192                 Qatar        Adult      5
180                  Peru        Adult      5
73                Finland        Adult      5
193                 Qatar        Teens      5
64                Denmark     Children      5
65                Denmark      General      5
195               Romania        Teens      4
74                Finland        Teens      4
185           Philippines      General      4
33                 Brazil     Children      4
26                Belgium      General      4
164           Netherlands     Children      4
155               Morocco        Teens      4
98                Iceland        Teens      4
143              Malaysia        Adult      4
176              Pakistan        Adult      4
204                Serbia        Adult      4
181                  Peru        Teens      4
126                Jordan        Teens      4
37               Cambodia        Adult      3
27                Belgium     Children      3
242                Turkey      General      3
107                  Iran        Teens      3
88                 Greece        Adult      3
85                  Ghana        Adult      3
205                Serbia        Teens      3
220          Soviet Union        Teens      3
208             Singapore     Children      3
119                 Italy      General      3
113               Ireland      General      3
128                 Kenya        Adult      3
124                 Japan      General      3
167           New Zealand     Children      3
144              Malaysia     Children      3
266               Vietnam        Adult      3
260               Uruguay        Teens      3
269          West Germany        Adult      3
267               Vietnam        Teens      3
10              Argentina     Children      2
261               Uruguay      General      2
4                 Algeria        Adult      2
263             Venezuela        Teens      2
172               Nigeria      General      2
145                 Malta        Adult      2
156               Morocco        Adult      2
129                 Kenya        Teens      2
160                 Nepal        Teens      2
201          Saudi Arabia        Adult      2
202               Senegal        Adult      2
80                Georgia        Teens      2
57                Croatia        Teens      2
233                 Syria        Teens      2
38               Cambodia        Teens      2
248  United Arab Emirates      General      2
244               Ukraine        Adult      2
272              Zimbabwe      General      2
253       United Kingdom,        Adult      2
75                Finland     Children      2
93              Hong Kong      General      2
56                Croatia        Adult      2
210              Slovenia        Adult      2
109                  Iraq        Adult      2
86                  Ghana        Teens      2
20             Bangladesh        Teens      2
265             Venezuela      General      1
148             Mauritius     Children      1
262          Vatican City        Teens      1
258        United States,        Adult      1
11                Armenia        Adult      1
6                  Angola        Adult      1
5                 Algeria        Teens      1
1                                Teens      1
268               Vietnam      General      1
270          West Germany      General      1
168           New Zealand      General      1
271          West Germany        Teens      1
169             Nicaragua        Adult      1
146                 Malta        Teens      1
147             Mauritius        Adult      1
2             Afghanistan        Adult      1
3                 Albania        Adult      1
0                                Adult      1
136         Liechtenstein        Teens      1
133                Latvia        Adult      1
132                Kuwait        Adult      1
130                 Kenya      General      1
191           Puerto Rico        Adult      1
190              Portugal        Teens      1
188               Poland,        Adult      1
182                  Peru      General      1
159               Namibia        Teens      1
179              Paraguay        Adult      1
178                Panama        Teens      1
177             Palestine        Teens      1
157            Mozambique        Adult      1
158               Namibia        Adult      1
153              Mongolia        Adult      1
154            Montenegro        Adult      1
264             Venezuela        Adult      1
203               Senegal        Teens      1
199                 Samoa        Teens      1
120               Jamaica        Adult      1
67           East Germany      General      1
90              Guatemala      General      1
95                Hungary     Children      1
66     Dominican Republic        Teens      1
89              Guatemala        Adult      1
106             Indonesia     Children      1
96                Hungary        Teens      1
127            Kazakhstan     Children      1
108                  Iran        Adult      1
137             Lithuania        Adult      1
141                Malawi        Teens      1
140            Luxembourg     Children      1
55               Colombia      General      1
215          South Africa      General      1
212               Somalia        Adult      1
211              Slovenia        Teens      1
209              Slovakia        Adult      1
68                Ecuador        Teens      1
71                  Egypt      General      1
72               Ethiopia        Adult      1
232           Switzerland      General      1
234                 Syria        Adult      1
35               Bulgaria        Teens      1
59                 Cyprus     Children      1
225             Sri Lanka      General      1
226                 Sudan        Adult      1
229                Sweden      General      1
58                   Cuba        Adult      1
45         Cayman Islands     Children      1
40               Cameroon        Adult      1
39              Cambodia,        Teens      1
36           Burkina Faso        Adult      1
239              Thailand      General      1
46         Cayman Islands        Teens      1
18             Azerbaijan        Teens      1
19                Bahamas        Teens      1
28                Bermuda        Teens      1
23                Belarus     Children      1
22             Bangladesh      General      1
21             Bangladesh        Adult      1
245               Ukraine        Teens      1
243                Uganda      General      1
29               Botswana        Teens      1
273              Zimbabwe        Adult      1

Kategori Adult mendominasi pada sebagian besar negara produksi, terutama pada negara United State. Sementara itu negara lain mendominasi pada kategori teens. Hal ini menunjukkan bahwa Netflix lebih fokus pada target audiens remaja hingga dewasa.

## 4. Genre konten netflix

In [36]:
df['listed_in'].value_counts().head()

listed_in
Dramas, International Movies                        485
Documentaries                                       423
Dramas, Independent Movies, International Movies    393
Stand-Up Comedy                                     335
Comedies, Dramas, International Movies              314
Name: count, dtype: int64

Genre Dramas dan Internasional Movie menjadi genre yang paling banyak tersedia di Netflix. Hal ini menunjukkan bahwa fokus terbesar Netflix menyediakan konten drama dan film internasional untuk menjangkau penggunaan global.

## 5. Distribusi kelompok usia

In [37]:
df['rating_group'].value_counts().head()

rating_group
Adult       4999
Teens       4605
Children     821
General      420
Name: count, dtype: int64

Kelompok usia Adult dan Teens memiliki jumlah konten tertinggi dibanding dengan Children dan General. Netflix lebih banyak menyediakan konten yang ditujukan untuk penonton remaja dan dewasa.

## 6. Perkembangan konten berdasar tahun rilis

In [57]:
df[['type','release_year']].value_counts().head()

type   release_year
Movie  2017            974
       2018            963
       2016            878
       2019            763
       2020            564
Name: count, dtype: int64

In [78]:
df[['type','release_year']].value_counts()

type     release_year
Movie    2017            974
         2018            963
         2016            878
         2019            763
         2020            564
         2015            544
TV Show  2020            490
         2019            445
         2018            427
Movie    2014            384
TV Show  2021            345
Movie    2021            313
TV Show  2017            302
Movie    2013            296
TV Show  2016            277
Movie    2012            231
         2010            215
         2011            194
TV Show  2015            184
Movie    2009            168
         2008            140
         2006            109
         2005            100
         2007             96
TV Show  2014             96
Movie    2003             77
         2004             72
TV Show  2012             71
         2013             70
Movie    2002             66
TV Show  2011             53
Movie    2001             50
TV Show  2010             47
Movie    2000             46
         1999             42
         1997             42
         1993             40
         1998             38
TV Show  2009             37
Movie    1992             28
TV Show  2008             25
Movie    1995             24
         1994             23
         1990             22
         1996             21
         1991             21
         1989             20
         1982             19
TV Show  2007             18
         2006             17
Movie    1988             16
TV Show  2005             15
Movie    1980             14
         1986             14
         1979             14
         1984             14
         1981             12
TV Show  2003             12
Movie    1973             11
         1983             11
TV Show  2002             10
Movie    1985             10
TV Show  1997             10
         2004              9
Movie    1976              9
TV Show  1999              9
Movie    1987              8
         1971              8
         1975              7
         1978              7
         1977              7
TV Show  2000              6
         1986              6
         1993              6
         1998              6
Movie    1974              6
         1968              5
         1960              5
         1965              5
TV Show  2001              5
         1996              5
Movie    1955              4
         1967              4
         1962              4
         1944              4
         1972              4
         1958              3
         1945              3
         1943              3
TV Show  1992              3
         1990              3
         1972              2
         1989              2
         1985              2
         1988              2
Movie    1969              2
         1964              2
         1954              2
         1942              2
TV Show  1994              2
Movie    1970              2
         1956              2
         1961              2
TV Show  1995              2
Movie    1947              1
         1963              1
         1946              1
         1966              1
         1959              1
TV Show  1974              1
         1967              1
         1925              1
         1977              1
         1979              1
         1981              1
         1945              1
         1946              1
         1963              1
         1991              1
Name: count, dtype: int64

konten rilisan terbanyak yaitu pada tahun 2017 untuk Movie dan tahun 2020 untuk TV show.

## 7. Perkembangan konten per tahun berdasar tahun ditambahkannya

In [75]:
df.groupby('type')['year_added'].value_counts()

type     year_added
Movie    2019          1773
         2020          1649
         2018          1566
         2021          1272
         2017          1091
         2016           334
         2015            73
         2014            25
         2011            17
         2013             6
         2012             4
         2009             2
         2008             1
         2010             1
TV Show  2020           697
         2019           647
         2021           558
         2018           472
         2017           383
         2016           224
         2015            33
         2014             9
         2013             7
         2008             1
Name: count, dtype: int64

Setelah tahun 2015, terjadi peningkatan yang signifikan dalam penambahan konten di Netflix dengan konten rilisan terbanyak pada tahun 2019.