#Import Library

In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Membaca Dataset

In [51]:
df = pd.read_excel("https://raw.github.com/dentawina/Dataset/main/dataset%20banking.xlsx"
)

In [52]:
df

,Booking_ID,CIF_Number,Booking_Date,Branch_Region,Branch_City,Product_Type,Product_Name,Txn_Count,Balance_Amount,Rate_Pct,Interest_Income,Operational_Cost,Acquisition_Source,Segment,Customer_Age,Risk_Score,Dormant_Flag,Target_Income
0,BAN-000001,CIF3955,23/01/2026,Yogyakarta,Sby,loan,Product_7,20,1887391.34,8.80,1973.30,2506.28,Branch,Mass,51,93,NaN,168783
1,BAN-000002,CIF2962,2024-07-25,Bandng,Surabaya,Savings,Product_60,5,2852671.52,21.52,4635.40,4874.07,Branch,Mass,23,8,N,321964
2,BAN-000003,CIF3190,06/09/2025,JKT,Jakarta,Loan,Product_66,11,4497505.58,-2.86,1993.41,2104.45,Referral,NaN,68,9,NaN,51096
3,BAN-000004,CIF1063,29/10/2024,Jakarta,Bandng,Loan,Product_18,10,4595829.52,-4.59,11.83,8.98,Referral,SME,44,95,NaN,537720
4,BAN-000005,CIF3948,Mar-31-2026,JKT,Sby,loan,Product_76,20,671473.94,5.00,2929.35,3076.07,Branch,NaN,70,80,NaN,922514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,BAN-009996,CIF1540,May-29-2024,Yogyakarta,Sby,Credit Card,Product_22,9,4419493.06,8.94,6331.97,6881.63,Referral,Mass,51,110,N,375135
9996,BAN-005649,CIF1420,14/12/2024,Jakarta,Jakarta,loan,Product_37,13,612618.35,16.32,3135.60,3670.06,Branch,NaN,68,41,N,786902
9997,BAN-009998,CIF1597,20/04/2024,Jakarta,Bandng,Loan,Product_32,14,3380285.52,7.53,10203.89,8435.50,Referral,Priority,34,68,Y,79837
9998,BAN-009999,CIF2729,2023-09-21,Bandung,Jakarta,Credit Card,Product_46,19,2347410.21,4.32,39.29,37.76,Branch,Mass,40,42,N,682711
9999,BAN-010000,CIF1750,Nov-30-2024,Bandng,Jakarta,Credit Card,Product_74,10,923018.40,12.51,1776.70,1470.68,Branch,Mass,31,90,Y,146286

#Dataset Info

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Booking_ID          10000 non-null  object
 1   CIF_Number          9412 non-null   object
 2   Booking_Date        10000 non-null  object
 3   Branch_Region       10000 non-null  object
 4   Branch_City         10000 non-null  object
 5   Product_Type        10000 non-null  object
 6   Product_Name        10000 non-null  object
 7   Txn_Count           10000 non-null  int64
 8   Balance_Amount      10000 non-null  float64
 9   Rate_Pct            10000 non-null  float64
 10  Interest_Income     10000 non-null  float64
 11  Operational_Cost    10000 non-null  float64
 12  Acquisition_Source  10000 non-null  object
 13  Segment             7480 non-null   object
 14  Customer_Age        10000 non-null  int64
 15  Risk_Score          10000 non-null  int64
 16  Dormant_Flag        6606 non-null   object
 17  Target_Income       10000 non-null  int64
dtypes: float64(4), int64(4), object(10)
memory usage: 1.4+ MB

In [54]:
df.isna().sum()

Booking_ID               0
CIF_Number             588
Booking_Date             0
Branch_Region            0
Branch_City              0
Product_Type             0
Product_Name             0
Txn_Count                0
Balance_Amount           0
Rate_Pct                 0
Interest_Income          0
Operational_Cost         0
Acquisition_Source       0
Segment               2520
Customer_Age             0
Risk_Score               0
Dormant_Flag          3394
Target_Income            0
dtype: int64

#Statistika Data

In [55]:
df.describe()

,Txn_Count,Balance_Amount,Rate_Pct,Interest_Income,Operational_Cost,Customer_Age,Risk_Score,Target_Income
count,10000.000000,1.000000e+04,10000.000000,1.000000e+04,1.000000e+04,10000.000000,10000.000000,10000.000000
mean,45.258300,2.476455e+06,9.925937,6.412797e+04,6.395578e+04,50.818700,60.028900,524175.922800
std,335.032267,1.449127e+06,8.676011,2.930601e+06,3.138755e+06,80.809175,35.196056,273348.870483
min,1.000000,-9.982950e+03,-4.990000,1.530000e+00,1.050000e+00,5.000000,0.000000,50022.000000
25%,6.000000,1.222703e+06,2.277500,6.460975e+02,5.630300e+02,31.000000,29.000000,293012.000000
50%,11.000000,2.467064e+06,9.910000,2.368230e+03,2.066425e+03,44.000000,60.000000,523179.000000
75%,16.000000,3.731119e+06,17.400000,6.011315e+03,5.221015e+03,58.000000,90.250000,758355.000000
max,4906.000000,4.999852e+06,25.000000,2.500502e+08,2.776007e+08,999.000000,120.000000,999995.000000

#Cek Missing Value

In [56]:
df.isnull().sum()

Booking_ID               0
CIF_Number             588
Booking_Date             0
Branch_Region            0
Branch_City              0
Product_Type             0
Product_Name             0
Txn_Count                0
Balance_Amount           0
Rate_Pct                 0
Interest_Income          0
Operational_Cost         0
Acquisition_Source       0
Segment               2520
Customer_Age             0
Risk_Score               0
Dormant_Flag          3394
Target_Income            0
dtype: int64

#Cek Data Duplikat

In [57]:
df.duplicated().sum()

np.int64(0)

In [58]:
product_counts = df['Product_Name'].value_counts()
display(product_counts)

Product_Name
Product_22    150
Product_33    146
Product_38    143
Product_31    140
Product_26    139
             ...
Product_51    106
Product_48    106
Product_53    105
Product_56    105
Product_30     99
Name: count, Length: 80, dtype: int64

#Data Cleaning dan Validation

##cek nilai unik booking id

In [59]:
df['Booking_ID'].nunique()

9591

Mengetahui jumlah transaksi atau pemesanan riil

##Isi Missing Value

In [60]:
df['CIF_Number'] = df['CIF_Number'].fillna('UNKNOWN')

In [61]:
df['CIF_Number'].value_counts(dropna=False)

CIF_Number
UNKNOWN    588
CIF3744      9
CIF1331      9
CIF1053      9
CIF1792      9
          ...
CIF1933      1
CIF1113      1
CIF1073      1
CIF4946      1
CIF1635      1
Name: count, Length: 3613, dtype: int64

##Isi Kolom Segment

In [62]:
# Cari batas segment dari distribusi balance
q1 = df['Balance_Amount'].quantile(0.33)
q2 = df['Balance_Amount'].quantile(0.66)

# Function isi segment
def fill_segment(balance):

    if pd.isna(balance):
        return np.nan

    elif balance <= q1:
        return 'Mass'

    elif balance <= q2:
        return 'SME'

    else:
        return 'Priority'

# Isi hanya yang kosong
mask = df['Segment'].isna()

df.loc[mask, 'Segment'] = (
    df.loc[mask, 'Balance_Amount']
    .apply(fill_segment)
)

##Isi Kolom Dormant

In [63]:
mask = df['Dormant_Flag'].isna()

df.loc[mask, 'Dormant_Flag'] = np.where(
    df.loc[mask, 'Txn_Count'] == 0,
    'Y',
    'N'
)

In [64]:
df['Dormant_Flag'].value_counts(dropna=False)

Dormant_Flag
N    6683
Y    3317
Name: count, dtype: int64

In [65]:
df['Dormant_Flag'].isna().sum()

np.int64(0)

In [66]:
# Cek hasil
df['Segment'].value_counts(dropna=False)

Segment
Priority    3360
Mass        3347
SME         3293
Name: count, dtype: int64

##Ganti tipe data booking date

In [67]:
df['Booking_Date'] = pd.to_datetime(df['Booking_Date'], format='mixed', dayfirst=True)

###cek missing value booking date

In [68]:
df['Booking_Date'].isna().sum()

np.int64(0)

##Cek data umur anomali

In [69]:
df[
    (df['Customer_Age'] < 17) |
    (df['Customer_Age'] > 100)
].count()

Booking_ID            225
CIF_Number            225
Booking_Date          225
Branch_Region         225
Branch_City           225
Product_Type          225
Product_Name          225
Txn_Count             225
Balance_Amount        225
Rate_Pct              225
Interest_Income       225
Operational_Cost      225
Acquisition_Source    225
Segment               225
Customer_Age          225
Risk_Score            225
Dormant_Flag          225
Target_Income         225
dtype: int64

In [70]:
df = df[
    (df['Customer_Age'] >= 17) &
    (df['Customer_Age'] <= 100)
]

In [71]:
df[
    (df['Customer_Age'] < 17) |
    (df['Customer_Age'] > 100)
].count()

Booking_ID            0
CIF_Number            0
Booking_Date          0
Branch_Region         0
Branch_City           0
Product_Type          0
Product_Name          0
Txn_Count             0
Balance_Amount        0
Rate_Pct              0
Interest_Income       0
Operational_Cost      0
Acquisition_Source    0
Segment               0
Customer_Age          0
Risk_Score            0
Dormant_Flag          0
Target_Income         0
dtype: int64

##Count Mising Value per kategorinya

In [72]:
df['Dormant_Flag'].value_counts()

Dormant_Flag
N    6528
Y    3247
Name: count, dtype: int64

##Benerin Isi Kolom Branch City

In [73]:
df['Branch_City'].unique()

array(['Sby', 'Surabaya', 'Jakarta', 'Bandng', 'Bandung', 'Jakrta',
       'Yogyakarta', 'Jogja'], dtype=object)

In [74]:
df['Product_Type'] = df['Product_Type'].str.title()

df['Branch_City'] = df['Branch_City'].replace({
    'Sby':'Surabaya',
    'Bdng':'Bandung',
    'Bandng':'Bandung',
    'Jakrta':'Jakarta',
    'Jogja':'Yogyakarta'
})

/tmp/ipykernel_6385/914510903.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Product_Type'] = df['Product_Type'].str.title()
/tmp/ipykernel_6385/914510903.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Branch_City'] = df['Branch_City'].replace({

In [75]:
df['Branch_City'].unique()

array(['Surabaya', 'Jakarta', 'Bandung', 'Yogyakarta'], dtype=object)

##Benerin Kolom Branch Region

In [76]:
df['Branch_Region'].unique()

array(['Yogyakarta', 'Bandng', 'JKT', 'Jakarta', 'SBY', 'Jogja',
       'JAKARTA', 'Jakrta', 'Bandung', 'Surabaya'], dtype=object)

In [77]:
df['Product_Type'] = df['Product_Type'].str.title()

df['Branch_Region'] = df['Branch_Region'].replace({
    'Bandng':'Bandung',
    'JKT':'Jakarta',
    'SBY':'Surabaya',
    'Jogja':'Yogyakarta',
    'JKT':'Jakarta',
    'Jakrta':'Jakarta',
    'JAKARTA':'Jakarta'
})

/tmp/ipykernel_6385/1284115602.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Product_Type'] = df['Product_Type'].str.title()
/tmp/ipykernel_6385/1284115602.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Branch_Region'] = df['Branch_Region'].replace({

In [78]:
df['Branch_Region'].unique()

array(['Yogyakarta', 'Bandung', 'Jakarta', 'Surabaya'], dtype=object)

#Cek Data Setelah di Isi Missing Valuenya

In [79]:
df.describe()

,Booking_Date,Txn_Count,Balance_Amount,Rate_Pct,Interest_Income,Operational_Cost,Customer_Age,Risk_Score,Target_Income
count,9775,9775.000000,9.775000e+03,9775.000000,9.775000e+03,9.775000e+03,9775.000000,9775.000000,9775.000000
mean,2025-01-23 02:12:26.148337408,44.972788,2.475984e+06,9.917439,6.492713e+04,6.490981e+04,43.939233,59.950895,524647.099744
min,2023-09-03 00:00:00,1.000000,-9.982950e+03,-4.990000,1.530000e+00,1.050000e+00,18.000000,0.000000,50022.000000
25%,2024-05-12 00:00:00,6.000000,1.217429e+06,2.260000,6.505900e+02,5.670400e+02,31.000000,29.000000,293216.500000
50%,2025-01-19 00:00:00,11.000000,2.466483e+06,9.900000,2.371020e+03,2.074120e+03,44.000000,60.000000,524146.000000
75%,2025-10-10 00:00:00,16.000000,3.732551e+06,17.410000,6.038400e+03,5.225120e+03,57.000000,90.000000,758706.500000
max,2026-06-19 00:00:00,4906.000000,4.999852e+06,25.000000,2.500502e+08,2.776007e+08,70.000000,120.000000,999995.000000
std,NaN,332.286066,1.450394e+06,8.678597,2.963890e+06,3.174555e+06,15.208522,35.132257,273313.673114

In [80]:
df

,Booking_ID,CIF_Number,Booking_Date,Branch_Region,Branch_City,Product_Type,Product_Name,Txn_Count,Balance_Amount,Rate_Pct,Interest_Income,Operational_Cost,Acquisition_Source,Segment,Customer_Age,Risk_Score,Dormant_Flag,Target_Income
0,BAN-000001,CIF3955,2026-01-23,Yogyakarta,Surabaya,Loan,Product_7,20,1887391.34,8.80,1973.30,2506.28,Branch,Mass,51,93,N,168783
1,BAN-000002,CIF2962,2024-07-25,Bandung,Surabaya,Savings,Product_60,5,2852671.52,21.52,4635.40,4874.07,Branch,Mass,23,8,N,321964
2,BAN-000003,CIF3190,2025-09-06,Jakarta,Jakarta,Loan,Product_66,11,4497505.58,-2.86,1993.41,2104.45,Referral,Priority,68,9,N,51096
3,BAN-000004,CIF1063,2024-10-29,Jakarta,Bandung,Loan,Product_18,10,4595829.52,-4.59,11.83,8.98,Referral,SME,44,95,N,537720
4,BAN-000005,CIF3948,2026-03-31,Jakarta,Surabaya,Loan,Product_76,20,671473.94,5.00,2929.35,3076.07,Branch,Mass,70,80,N,922514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,BAN-009996,CIF1540,2024-05-29,Yogyakarta,Surabaya,Credit Card,Product_22,9,4419493.06,8.94,6331.97,6881.63,Referral,Mass,51,110,N,375135
9996,BAN-005649,CIF1420,2024-12-14,Jakarta,Jakarta,Loan,Product_37,13,612618.35,16.32,3135.60,3670.06,Branch,Mass,68,41,N,786902
9997,BAN-009998,CIF1597,2024-04-20,Jakarta,Bandung,Loan,Product_32,14,3380285.52,7.53,10203.89,8435.50,Referral,Priority,34,68,Y,79837
9998,BAN-009999,CIF2729,2023-09-21,Bandung,Jakarta,Credit Card,Product_46,19,2347410.21,4.32,39.29,37.76,Branch,Mass,40,42,N,682711
9999,BAN-010000,CIF1750,2024-11-30,Bandung,Jakarta,Credit Card,Product_74,10,923018.40,12.51,1776.70,1470.68,Branch,Mass,31,90,Y,146286

#Feature Engineering

##1. Tambah Tabel Target

###cek apakah ada target income yang 0

In [81]:
target_achievement = (
    df['Interest_Income'].sum()
    /
    df['Target_Income'].sum()
) * 100

print(target_achievement)

12.375390609952131

In [82]:
df['Target_Achievement'] = (
    (
        df['Interest_Income']
        /
        df['Target_Income']
    ) * 100
).round(2)

/tmp/ipykernel_6385/4170980512.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Target_Achievement'] = (

In [83]:
df['Target_Achievement'].describe()

count     9775.000000
mean        17.436975
std        667.172470
min          0.000000
25%          0.140000
50%          0.510000
75%          1.430000
max      51332.070000
Name: Target_Achievement, dtype: float64

Seberapa besar pendapatan aktual yang berhasil dicapai dibanding target pendapatan yang sudah ditentukan bank.

Jadi dia dipakai buat ukur apakah performanya sudah sesuai ekspektasi atau belum.

#2. Tambah tabel profit

In [84]:
df['Profit'] = (
    df['Interest_Income'] - df['Operational_Cost']
)

/tmp/ipykernel_6385/3485833251.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit'] = (

In [85]:
df['Profit'].describe()

count    9.775000e+03
mean     1.731355e+01
std      2.891552e+05
min     -2.755046e+07
25%     -1.133000e+02
50%      6.755000e+01
75%      6.960450e+02
max      6.305551e+06
Name: Profit, dtype: float64

##3. Tambah Tabel Profit Margin

##cek apakah interest income ada yang 0

In [86]:
(df['Interest_Income'] == 0).sum()

np.int64(0)

In [87]:
df['Profit_Margin'] = (
    df['Profit']
    /
    df['Interest_Income']
) * 100

/tmp/ipykernel_6385/3512350829.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit_Margin'] = (

In [88]:
df['Profit_Margin'].describe()

count    9775.000000
mean        9.813338
std        23.070258
min       -29.981382
25%        -9.772647
50%         9.516153
75%        30.164321
max        49.984612
Name: Profit_Margin, dtype: float64

##4. Tambah Tabel Age Group

In [89]:
bins = [18, 25, 40, 60, float('inf')]

labels = [
    'Gen Z',
    'Young Adult',
    'Mature',
    'Senior'
]

df['Age_Group'] = pd.cut(
    df['Customer_Age'],
    bins=bins,
    labels=labels,
    include_lowest=True
)

/tmp/ipykernel_6385/2721801523.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age_Group'] = pd.cut(

###Cek Hasil Age Group

In [90]:
df[
[
'Customer_Age',
'Age_Group'
]
].head()

   Customer_Age Age_Group
0            51    Mature
1            23     Gen Z
2            68    Senior
3            44    Mature
4            70    Senior

In [91]:
df['Age_Group'].value_counts()

Age_Group
Mature         3730
Young Adult    2803
Senior         1804
Gen Z          1438
Name: count, dtype: int64

#Ubah Format Tanggal yang 2026 jadi 2025

In [92]:
df.loc[
    df['Booking_Date'].dt.year == 2026,
    'Booking_Date'
] = df.loc[
    df['Booking_Date'].dt.year == 2026,
    'Booking_Date'
].apply(lambda x: x.replace(year=2025))

In [93]:
df

,Booking_ID,CIF_Number,Booking_Date,Branch_Region,Branch_City,Product_Type,Product_Name,Txn_Count,Balance_Amount,Rate_Pct,...,Acquisition_Source,Segment,Customer_Age,Risk_Score,Dormant_Flag,Target_Income,Target_Achievement,Profit,Profit_Margin,Age_Group
0,BAN-000001,CIF3955,2025-01-23,Yogyakarta,Surabaya,Loan,Product_7,20,1887391.34,8.80,...,Branch,Mass,51,93,N,168783,1.17,-532.98,-27.009578,Mature
1,BAN-000002,CIF2962,2024-07-25,Bandung,Surabaya,Savings,Product_60,5,2852671.52,21.52,...,Branch,Mass,23,8,N,321964,1.44,-238.67,-5.148854,Gen Z
2,BAN-000003,CIF3190,2025-09-06,Jakarta,Jakarta,Loan,Product_66,11,4497505.58,-2.86,...,Referral,Priority,68,9,N,51096,3.90,-111.04,-5.570354,Senior
3,BAN-000004,CIF1063,2024-10-29,Jakarta,Bandung,Loan,Product_18,10,4595829.52,-4.59,...,Referral,SME,44,95,N,537720,0.00,2.85,24.091293,Mature
4,BAN-000005,CIF3948,2025-03-31,Jakarta,Surabaya,Loan,Product_76,20,671473.94,5.00,...,Branch,Mass,70,80,N,922514,0.32,-146.72,-5.008620,Senior
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,BAN-009996,CIF1540,2024-05-29,Yogyakarta,Surabaya,Credit Card,Product_22,9,4419493.06,8.94,...,Referral,Mass,51,110,N,375135,1.69,-549.66,-8.680711,Mature
9996,BAN-005649,CIF1420,2024-12-14,Jakarta,Jakarta,Loan,Product_37,13,612618.35,16.32,...,Branch,Mass,68,41,N,786902,0.40,-534.46,-17.044904,Senior
9997,BAN-009998,CIF1597,2024-04-20,Jakarta,Bandung,Loan,Product_32,14,3380285.52,7.53,...,Referral,Priority,34,68,Y,79837,12.78,1768.39,17.330547,Young Adult
9998,BAN-009999,CIF2729,2023-09-21,Bandung,Jakarta,Credit Card,Product_46,19,2347410.21,4.32,...,Branch,Mass,40,42,N,682711,0.01,1.53,3.894121,Young Adult
9999,BAN-010000,CIF1750,2024-11-30,Bandung,Jakarta,Credit Card,Product_74,10,923018.40,12.51,...,Branch,Mass,31,90,Y,146286,1.21,306.02,17.224067,Young Adult

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9775 entries, 0 to 9999
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Booking_ID          9775 non-null   object
 1   CIF_Number          9775 non-null   object
 2   Booking_Date        9775 non-null   datetime64[ns]
 3   Branch_Region       9775 non-null   object
 4   Branch_City         9775 non-null   object
 5   Product_Type        9775 non-null   object
 6   Product_Name        9775 non-null   object
 7   Txn_Count           9775 non-null   int64
 8   Balance_Amount      9775 non-null   float64
 9   Rate_Pct            9775 non-null   float64
 10  Interest_Income     9775 non-null   float64
 11  Operational_Cost    9775 non-null   float64
 12  Acquisition_Source  9775 non-null   object
 13  Segment             9775 non-null   object
 14  Customer_Age        9775 non-null   int64
 15  Risk_Score          9775 non-null   int64
 16  Dormant_Flag        9775 non-null   object
 17  Target_Income       9775 non-null   int64
 18  Target_Achievement  9775 non-null   float64
 19  Profit              9775 non-null   float64
 20  Profit_Margin       9775 non-null   float64
 21  Age_Group           9775 non-null   category
dtypes: category(1), datetime64[ns](1), float64(7), int64(4), object(9)
memory usage: 1.7+ MB

#Push Data ke DBeaver

In [95]:
from sqlalchemy import create_engine

In [96]:
DATABASE_URL = (
"postgresql://postgres.ssgquzqdkmuqaudouvxo:aaiinnii2003@aws-1-ap-south-1.pooler.supabase.com:6543/postgres"
)

engine = create_engine(DATABASE_URL)

In [97]:
df.to_sql(
    'banking',
    engine,
    if_exists='replace',
    index=False
)

775